config/routes.rb
Microblog::Application.routes.draw do
  resources :users do
    resources :microposts, :only => [:index, :create, :destroy]
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %div#error_explanation
    %h2
      = pluralize object.errors.count, "error"
      prohibited this 
      = object.class.to_s.underscore.humanize.downcase
      form being saved
    %p There were problems with the following fields:
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- unless @feed_items.empty?
  %table.microposts{:summary => 'User microposts'}
    = render :partial => 'shared/feed_item', :collection => @feed_items

app/views/shared/_feed_item.html.haml
%tr
  %td.gravatar
    = link_to gravatar_for(feed_item.user), feed_item.user
  %td.micropost
    %span.user= link_to feed_item.user.name, feed_item.user
    %span.content= wrap feed_item.content
    %span.timestamp
      Posted
      = time_ago_in_words(feed_item.created_at)
      ago.

app/views/shared/_follow.html.haml
= form_for current_user.relationships.build(:followed_id => @user.id) do |f| 
  %div
    = f.hidden_field :followed_id
  %div{:class => "actions"}
    = f.submit "Follow"

app/views/shared/_follow_form.html.haml
- unless current_user?(@user)
  %div{:id => "follow_form"}
  - if current_user.following?(@user) 
    = render 'shared/unfollow'
  - else
    = render 'shared/follow'

app/views/shared/_index.html.haml
%table.profile{:summary => 'Profile information'}
  %tr
    %td{:class => 'main'}
      %h1
        = gravatar_for @user
        = @user.name
      = render 'shared/follow_form' if signed_in?
      - unless @user.microposts.empty?
        %table.microposts{:summary => 'User microposts'}
          = render @microposts
        = will_paginate @microposts
    %td{:class => 'sidebar round'}
      %strong Name
      = @user.name
      %br
      %strong Link
      = link_to 'Microposts', user_microposts_path(@user)
      %br
      %strong Microposts
      = @user.microposts.count
      = render 'shared/stats'

app/views/shared/_micropost_form.html.haml
= form_for [current_user, @micropost] do |f|
  = render 'shared/error_messages', :object => f.object
  %div.field= f.text_area :content
  %div.actions= f.submit 'Submit'

app/views/shared/_signed_in.html.haml
%table.front{:summary => 'For signed-in users'}
  %tr
    %td{:class => 'main'}
      %h1.micropost What's up?
      = render 'shared/micropost_form'
      = render 'shared/feed'
    %td{:class => 'sidebar round'}
      = render 'shared/user_info'
      = render 'shared/stats'

app/views/shared/_signed_out.html.haml
%h1= @page_title

%p
  Sleeping, lost, and numb. 
  So glad that I have found you. 
  I am wide awake and heading home. 
%p
  Hold your light, 
  Eleven. 
  Lead me through each gentle step by step 
  by inch by loaded memory. 
  I'll move to heal 
  As soon as pain allows so we can 
  Reunite and both move on together. 
%p
  Hold your light, 
  Eleven. Lead me through each gentle step by step 
  By inch by loaded memory 
  'till one and one are one, eleven, 

= link_to 'Sign up now!', signup_path, :class => 'signup_button round'

app/views/shared/_stats.html.haml
- @user ||= current_user
%div.stats
  %a{:href => following_user_path(@user)}
    %span{:id => "following", :class => "stat"}
      = "#{@user.following.count} following"
  %a{:href => followers_user_path(@user)}
    %span{:id => "followers", :class => "stat"}
      = pluralize(@user.followers.count, "follower")

app/views/shared/_unfollow.html.haml
= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete } do |f|
  %div{:class => "actions"}
    = f.submit "Unfollow"

app/views/shared/_user_info.html.haml
%div.user_info
  %a{:href =>  user_path(current_user)}
    = gravatar_for(current_user, :size => 30)
    %span.user_name= current_user.name
    %span.microposts= pluralize(current_user.microposts.count, 'micropost')