config/routes.rb
Microblog::Application.routes.draw do
  resources :users do
    resources :microposts, :only => [:index, :create, :destroy]
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li 
        So glow, child, glow. 
      %li
        I'm heading back home

app/views/layouts/_header.html.haml
%header
  = link_to logo_tag, root_path
  %nav.round
    %ul
      %li= link_to 'Home', root_path
      - if signed_in?
        %li= link_to 'Users', users_path
        %li= link_to 'Profile', current_user
        %li= link_to 'Settings', edit_user_path(current_user)
        %li= link_to 'Sign out', signout_path, :method => :delete
      - else
        %li= link_to 'Sign in', signin_path

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print',  :media => 'print'
= stylesheet_link_tag 'custom', :media => 'screen'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %div.container 
      = render 'layouts/header'
      %section.round
        - flash.each do |key, value|
          = content_tag :div, value, :class => "flash #{key}"
        = yield
      = render 'layouts/footer'